--!strict

return {
	BODY_FATIGUE_MAX = 100,

	SOFT_CAP_PERCENT = 65,
	FORTITUDE_CAP_PERCENT = 85,

	NO_SWEAT_DECAY_DELAY = 5 * 60,
	BASE_DECAY_RATE = 1.25, -- Fatigue points per second

	HIGH_FATIGUE_STAMINA_DRAIN_MULTIPLIER = 1.4,
	HIGH_FATIGUE_GAIN_MULTIPLIER = 1.25,
}