--!strict

return {
	PASSIVE_HUNGER_DRAIN_RATE = 0.05,
	PASSIVE_HUNGER_DRAIN_INTERVAL = 1,
	STAMINA_TO_HUNGER_RATIO = 0.065,

	HUNGER_CRITICAL_THRESHOLD = 20,
	HUNGER_FULL_THRESHOLD = 70,

	MUSCLE_LOSS_RATE = 0.25,
	MUSCLE_LOSS_INTERVAL = 1.5,

	FAT_GAIN_RATE = 0.015,
	FAT_GAIN_INTERVAL = 0.75,

	FAT_LOSS_RATE = 0.05,
	FAT_LOSS_INTERVAL = 0.75,

	FAT_HARD_CAP = 650,

	STAT_GAIN_MULTIPLIER_STARVING = 0.25,
	STAT_GAIN_MULTIPLIER_NORMAL = 1.0,
	STAT_GAIN_THRESHOLD = 5,
}