--!strict

return {
	SPRINT_STAMINA_COST_PER_SECOND = 8,
	JOG_STAMINA_COST_PER_SECOND = 3,

	STAMINA_REGEN_RATE = 5,
	STAMINA_REGEN_DELAY = 0.25,

	DRAINED_THRESHOLD = 45,
	EXHAUSTED_REGEN_MULTIPLIER = 0.5,
	EXHAUSTED_REMOVAL_THRESHOLD = 15,

	BASE_MAX_STAMINA = 75,
}