--!strict

local States = {
	RAGDOLLED = "Ragdolled",
	ATTACKING = "Attacking",
	INVULNERABLE = "Invulnerable",
	STUNNED = "Stunned",
	BLOCKING = "Blocking",
	PARRYING = "Parrying",
	PARRIED = "Parried",
	CLASHING = "Clashing",
	DOWNED = "Downed",
	KILLED = "Killed",
	SPRINTING = "Sprinting",
	JOGGING = "Jogging",
	JUMPING = "Jumping",
	FALLING = "Falling",
	IN_CUTSCENE = "InCutscene",
	GUARD_BROKEN = "GuardBroken",
	RIPOSTE_WINDOW = "RiposteWindow",
	DODGING = "Dodging",
	IFRAME = "Iframe",
	MODE_ACTIVE = "ModeActive",
	STAGGERED = "Staggered",
	BLINDED = "Blinded",
	BLEEDING = "Bleeding",
	SLUGGISH = "Sluggish",
	FATIGUED = "Fatigued",
	DIZZY = "Dizzy",
}

local Events = {
	DAMAGE_TAKEN = "DamageTaken",
	DAMAGE_DEALT = "DamageDealt",
	ATTACK_STARTED = "AttackStarted",
	ATTACK_HIT = "AttackHit",
	KILLED_ENEMY = "KilledEnemy",
	PARRY_SUCCESS = "ParrySuccess",
	PARRY_FAILED = "ParryFailed",
	BLOCK_SUCCESS = "BlockSuccess",
	PERFECT_BLOCK = "PerfectBlock",
	POSTURE_BREAK = "PostureBreak",
	RIPOSTE_STARTED = "RiposteStarted",
	SPRINT_STARTED = "SprintStarted",
	SPRINT_STOPPED = "SprintStopped",
	JOG_STARTED = "JogStarted",
	JOG_STOPPED = "JogStopped",
	DODGE_STARTED = "DodgeStarted",
	SKILL_USED = "SkillUsed",
	MODE_ACTIVATED = "ModeActivated",
	MODE_DEACTIVATED = "ModeDeactivated",
	STAMINA_DEPLETED = "StaminaDepleted",
	HUNGER_CRITICAL = "HungerCritical",
}

return {
	States = States,
	Events = Events,
}